- get_url: dest={{ osm_pgsql.pbf_file }} url={{ osm_pgsql.pbf_url }} mode=666
- apt: pkg={{ item }} state=present
  with_items:
  - osm2pgsql
  - postgresql
  - postgresql-9.3-postgis-2.1
  sudo: true
- template: src=import dest=/tmp/import mode=777
- shell: sudo -i -u postgres /tmp/import
- file: name={{ osm_pgsql.pbf_file }} mode=666
- service: name=postgresql state=restarted
  sudo: true
